id: IA1946161
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-02-02T17:40:27+00:00'
last_modified: '2022-06-16T05:06:21.740083+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC375
  title: 'རས་ཆུང་སྙན་བརྒྱུད་སྐོར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6D0C:
      image_group_id: I4PD2758
      title: ''
      total_pages: 558
      order: 1
      base_file: 6D0C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
